# Generated by Django 3.0.6 on 2020-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('contiR', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
