# Generated by Django 3.0.6 on 2020-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='date',
            new_name='U_date',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='desc',
            new_name='U_desc',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='heading',
            new_name='U_heading',
        ),
    ]
