# Generated by Django 3.0.6 on 2020-08-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20200814_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_img', models.ImageField(upload_to='pics')),
                ('G_heading', models.CharField(max_length=100)),
                ('G_desc', models.TextField()),
            ],
        ),
    ]
